/** Known IANA timezone identifiers used for browser country detection. */
const TIMEZONE_COUNTRY_MAP: Readonly<Record<string, string>> = {
  'Europe/Zurich': 'CH',
  'Europe/Berlin': 'DE',
  'Europe/Busingen': 'DE',
  'Europe/Paris': 'FR',
  'Europe/London': 'GB',
  'Europe/Dublin': 'IE',
  'America/Toronto': 'CA',
  'America/Vancouver': 'CA',
  'Australia/Sydney': 'AU',
  'Australia/Melbourne': 'AU',
  'Pacific/Auckland': 'NZ',

  // Canonical US zones from IANA zone.tab.
  'America/New_York': 'US',
  'America/Detroit': 'US',
  'America/Kentucky/Louisville': 'US',
  'America/Kentucky/Monticello': 'US',
  'America/Indiana/Indianapolis': 'US',
  'America/Indiana/Vincennes': 'US',
  'America/Indiana/Winamac': 'US',
  'America/Indiana/Marengo': 'US',
  'America/Indiana/Petersburg': 'US',
  'America/Indiana/Vevay': 'US',
  'America/Chicago': 'US',
  'America/Indiana/Tell_City': 'US',
  'America/Indiana/Knox': 'US',
  'America/Menominee': 'US',
  'America/North_Dakota/Center': 'US',
  'America/North_Dakota/New_Salem': 'US',
  'America/North_Dakota/Beulah': 'US',
  'America/Denver': 'US',
  'America/Boise': 'US',
  'America/Phoenix': 'US',
  'America/Los_Angeles': 'US',
  'America/Anchorage': 'US',
  'America/Juneau': 'US',
  'America/Sitka': 'US',
  'America/Metlakatla': 'US',
  'America/Yakutat': 'US',
  'America/Nome': 'US',
  'America/Adak': 'US',
  'Pacific/Honolulu': 'US',

  // IANA backward links that browsers and older runtimes may expose.
  'US/Alaska': 'US',
  'US/Aleutian': 'US',
  'US/Arizona': 'US',
  'US/Central': 'US',
  'US/East-Indiana': 'US',
  'US/Eastern': 'US',
  'US/Hawaii': 'US',
  'US/Indiana-Starke': 'US',
  'US/Michigan': 'US',
  'US/Mountain': 'US',
  'US/Pacific': 'US',
  'America/Indianapolis': 'US',
  'America/Knox_IN': 'US',
  'America/Louisville': 'US',
};

export function countryForTimezone(timezone: string): string | undefined {
  return TIMEZONE_COUNTRY_MAP[timezone];
}
