package com.x8ing.mtl.server.mtlserver.db.entity.gps;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import tools.jackson.databind.annotation.JsonSerialize;
import com.x8ing.mtl.server.mtlserver.db.entity.indexer.IndexedFile;
import com.x8ing.mtl.server.mtlserver.web.global.GeoDoubleSerializer;
import jakarta.persistence.*;
import lombok.Data;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Entity
@Data
@JsonPropertyOrder({
        "id",
        "indexedFile",
        "creator",
        "gpxVersion",
        "metaName",
        "metaDescription",
        "metaLink",
        "metaTime",
        "metaAuthor",
        "trackName",
        "trackType",
        "trackDescription",
        "startDate",
        "endDate",
        "trackDurationInMotionSecs",
        "trackDurationStoppedSecs",
        "trackStopCount",
        "trackLongestStopSecs",
        "maxDistanceBetweenPoints",
        "medianDistanceBetweenPoints",
        "avgDistanceBetweenPoints",
        "didFilterOutlierByDistance",
        "numberOfTrackPoints",
        "trackLengthInMeter",
        "ascentInMeter",
        "descentInMeter",
        "minAltitude",
        "maxAltitude",
        "speedInKmh30sMax",
        "elevationGainPerHour30sMax",
        "elevationLossPerHour30sMax",
        "slopePercentageMax",
        "slopePercentageMin",
        "utmZone",
        "loadStatus",
        "loadMessages",
        "duplicateStatus",
        "duplicateOf",
        "duplicateDetails",
        "gpsTracksData",
        "activityType",
        "activityTypeSource",
        "activityTypeSourceDetails",
        "highlightExclusionReason",
        "statisticsExclusionReason",
        "garminActivityId",
        "bboxMinLat",
        "bboxMaxLat",
        "bboxMinLng",
        "bboxMaxLng",
        "centerLat",
        "centerLng",
        "energyGravitationalTotalWh",
        "energyGravitationalDescentWh",
        "energyAeroDragTotalWh",
        "energyRollingResistanceTotalWh",
        "energyKineticPositiveTotalWh",
        "energyNetTotalWh",
        "energyWeightKgUsed",
        "powerWattsAvg",
        "powerWattsMovingAvg",
        "powerWattsMax",
        "powerWatts30sMax",
        "normalizedPowerWatts",
        "explorationStatus",
        "explorationScore",
        "explorationCalcDate",
        "sourceSegmentIndex",
        "sourceParentTrackId",
        "trackSource",
        "plannerWaypointsJson",
        "plannerProfile",
        "plannerRouteJson",
        "createDate",
        "updateDate",
        "version"
})
public class GpsTrack {


    public enum LOAD_STATUS {
        SUCCESS, FAILED, EMPTY_FILE
    }

    public enum DUPLICATE_CHECK_STATUS {
        NOT_CHECKED_YET, DUPLICATE, UNIQUE, EXCLUDED
    }

    public enum ACTIVITY_TYPE {
        BICYCLE, CAR, WALKING, HIKING, STAND_UP_PADDLE, RUNNING, MOUNTAIN_BIKING, ROWING, KAYAKING, MOTORBIKING, AIRPLANE, SKIING, SUPER_SONIC
    }

    public enum ACTIVITY_TYPE_SOURCE {
        AUTO_GUESS, USER_SET, FAILED
    }

    public enum STATISTICS_EXCLUSION_REASON {
        GPS_NOISE, WRONG_ACTIVITY, IMPORT_ARTIFACT, OTHER
    }

    public enum EXPLORATION_STATUS {
        NOT_SCHEDULED, SCHEDULED, IN_PROGRESS, CALCULATED, NEEDS_RECALCULATION
    }

    /**
     * Origin of this track.
     * <ul>
     *   <li>{@link #IMPORTED} — default; track came from a GPX file (recorded, Garmin, manual upload).
     *       These tracks participate in statistics, duplicate detection, exploration scoring, etc.</li>
     *   <li>{@link #PLANNED} — synthetic track generated by the in-app route planner.
     *       Excluded from every "real" track surface (stats/duplicates/exploration/default map).
     *       Lives only in the planner UI and the "My Plans" list.</li>
     * </ul>
     */
    public enum TRACK_SOURCE {
        IMPORTED, PLANNED
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "file_id", referencedColumnName = "id")
    private IndexedFile indexedFile;

    @Column(length = 4000)
    private String creator;

    private String gpxVersion;

    @Column(length = 4000)
    private String metaName;

    @Column(length = 4000)
    private String metaDescription;

    @Column(length = 4000)
    private String metaLink;

    private Date metaTime;

    @Column(length = 4000)
    private String metaAuthor;

    @Column(length = 4000)
    private String trackName;

    @Column(length = 4000)
    private String trackType;

    @Column(length = 8000)
    private String trackDescription;

    private Date startDate;

    private Date endDate;

    /**
     * Duration in seconds where speed >= 0.5 km/h (moving time only, excludes stops/idle).
     */
    private Double trackDurationInMotionSecs;

    /**
     * Total time in seconds the track was detected as "stopped" by the dense
     * GPS stop detector. Computed over the outlier-cleaned point stream at
     * ingest. Unlike {@code trackDuration - trackDurationInMotionSecs}, this
     * excludes "gap" time where the GPS simply stopped recording.
     */
    private Double trackDurationStoppedSecs;

    /**
     * Number of distinct stops detected during the track (see {@link #trackDurationStoppedSecs}).
     */
    private Integer trackStopCount;

    /**
     * Duration in seconds of the single longest detected stop.
     */
    private Double trackLongestStopSecs;

    private Double maxDistanceBetweenPoints;

    private Double medianDistanceBetweenPoints;

    private Double avgDistanceBetweenPoints;

    private Boolean didFilterOutlierByDistance;

    private Integer numberOfTrackPoints;

    private Double trackLengthInMeter;

    /**
     * Canonical accumulated ascent in metres, computed from the full
     * RAW_OUTLIER_CLEANED point stream after elevation denoising.
     */
    @Column(name = "ascent_in_meter")
    private Double ascentInMeter;

    /**
     * Canonical accumulated descent in metres, computed from the full
     * RAW_OUTLIER_CLEANED point stream after elevation denoising.
     */
    @Column(name = "descent_in_meter")
    private Double descentInMeter;

    @Column(name = "min_altitude")
    private Double minAltitude;

    @Column(name = "max_altitude")
    private Double maxAltitude;

    /**
     * Peak trailing 30-second average speed in km/h, computed on the canonical
     * dense point stream.
     */
    @Column(name = "speed_in_kmh_30s_max")
    private Double speedInKmh30sMax;

    /**
     * Peak trailing 30-second elevation-gain rate in m/h, computed on the
     * canonical dense point stream.
     */
    @Column(name = "elevation_gain_per_hour_30s_max")
    private Double elevationGainPerHour30sMax;

    /**
     * Peak trailing 30-second elevation-loss rate in m/h, computed on the
     * canonical dense point stream.
     */
    @Column(name = "elevation_loss_per_hour_30s_max")
    private Double elevationLossPerHour30sMax;

    /**
     * Canonical maximum moving-window slope percentage from RAW_OUTLIER_CLEANED.
     */
    @Column(name = "slope_percentage_max")
    private Double slopePercentageMax;

    /**
     * Canonical minimum moving-window slope percentage from RAW_OUTLIER_CLEANED.
     */
    @Column(name = "slope_percentage_min")
    private Double slopePercentageMin;

    private String utmZone;

    @Enumerated(EnumType.STRING)
    private LOAD_STATUS loadStatus;

    @Column(length = 8000)
    private String loadMessages;

    @Enumerated(EnumType.STRING)
    private DUPLICATE_CHECK_STATUS duplicateStatus = DUPLICATE_CHECK_STATUS.NOT_CHECKED_YET;

    private Long duplicateOf;

    @Column(length = 4000)
    private String duplicateDetails;

    // Trouble @OneToMany(mappedBy = "gpsTrack", cascade = CascadeType.DETACH, fetch = FetchType.LAZY)
    @Transient
    private List<GpsTrackData> gpsTracksData = new ArrayList<>();

    @Enumerated(EnumType.STRING)
    private ACTIVITY_TYPE activityType;

    @Enumerated(EnumType.STRING)
    private ACTIVITY_TYPE_SOURCE activityTypeSource;

    private String activityTypeSourceDetails;

    @Enumerated(EnumType.STRING)
    @Column(name = "highlight_exclusion_reason")
    private STATISTICS_EXCLUSION_REASON highlightExclusionReason;

    @Enumerated(EnumType.STRING)
    @Column(name = "statistics_exclusion_reason")
    private STATISTICS_EXCLUSION_REASON statisticsExclusionReason;

    private String garminActivityId;

    // Bounding box and centroid of the track (computed at scan time from the cleaned geometry)
    @JsonSerialize(using = GeoDoubleSerializer.class)
    private Double bboxMinLat;
    @JsonSerialize(using = GeoDoubleSerializer.class)
    private Double bboxMaxLat;
    @JsonSerialize(using = GeoDoubleSerializer.class)
    private Double bboxMinLng;
    @JsonSerialize(using = GeoDoubleSerializer.class)
    private Double bboxMaxLng;
    @JsonSerialize(using = GeoDoubleSerializer.class)
    private Double centerLat;
    @JsonSerialize(using = GeoDoubleSerializer.class)
    private Double centerLng;

    // ── Energy totals (populated by EnergyService, all energy values in Wh, power in W) ──

    @Column(name = "energy_gravitational_total_wh")
    private Double energyGravitationalTotalWh;

    @Column(name = "energy_gravitational_descent_wh")
    private Double energyGravitationalDescentWh;

    @Column(name = "energy_aero_drag_total_wh")
    private Double energyAeroDragTotalWh;

    @Column(name = "energy_rolling_resistance_total_wh")
    private Double energyRollingResistanceTotalWh;

    @Column(name = "energy_kinetic_positive_total_wh")
    private Double energyKineticPositiveTotalWh;

    @Column(name = "energy_net_total_wh")
    private Double energyNetTotalWh;

    /**
     * Total rider/person plus equipment/vehicle mass used by the energy model.
     */
    @Column(name = "energy_weight_kg_used")
    private Double energyWeightKgUsed;

    @Column(name = "power_watts_avg")
    private Double powerWattsAvg;

    @Column(name = "power_watts_moving_avg")
    private Double powerWattsMovingAvg;

    @Column(name = "power_watts_max")
    private Double powerWattsMax;

    /**
     * Peak trailing 30-second average of estimated mechanical power.
     * More stable than {@link #powerWattsMax}, which is the raw per-segment peak.
     */
    @Column(name = "power_watts_30s_max")
    private Double powerWatts30sMax;

    /**
     * Normalized Power (W) — a variability-weighted average of instantaneous power
     * computed from a 30-second rolling mean raised to the 4th power, averaged, then
     * 4th-rooted. Better reflects physiological effort than a simple average because
     * hard bursts weigh disproportionately more than steady easy output.
     * <p>
     * Industry aliases: Weighted Average Power (Strava), Normalized Power / NP
     * (Garmin, TrainingPeaks), xPower / IsoPower (GoldenCheetah).
     */
    @Column(name = "normalized_power_watts")
    private Double normalizedPowerWatts;

    // ── Exploration Score (computed by background job, see doc/exploration/EXPLORATION_SCORE.md) ──

    @Enumerated(EnumType.STRING)
    @Column(name = "exploration_status")
    private EXPLORATION_STATUS explorationStatus = EXPLORATION_STATUS.NOT_SCHEDULED;

    @Column(name = "exploration_score")
    private Double explorationScore;

    @Column(name = "exploration_calc_date")
    private Date explorationCalcDate;

    // ── Segment splitting (temporal gap detection splits one GPX file into multiple GpsTracks) ──

    /**
     * NULL = whole track (no split); 1, 2, ... = Nth segment from a time-gap split
     */
    private Integer sourceSegmentIndex;

    /**
     * FK to the master segment (segment 1) when this track was derived from a file with temporal gaps.
     * NULL for the master segment itself and for unsplit tracks.
     */
    private Long sourceParentTrackId;

    /**
     * Origin of this track — IMPORTED (default, from GPX) or PLANNED (from the route planner).
     * PLANNED tracks are excluded by default from statistics, duplicate detection, exploration,
     * activity classification and the main map (via the central SmartBaseFilter + per-job queries).
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "track_source", nullable = false)
    private TRACK_SOURCE trackSource = TRACK_SOURCE.IMPORTED;

    /**
     * Original user waypoints for PLANNED tracks, encoded as a JSON array of
     * {@code {"lat":.., "lng":..}} objects (waypoint order preserved). NULL for
     * IMPORTED tracks. Used by the planner UI to re-hydrate an editable route
     * (draggable markers + recompute) when the user re-opens a saved plan.
     */
    @Column(name = "planner_waypoints_json", length = 8000)
    private String plannerWaypointsJson;

    /**
     * BRouter routing profile used to build the saved plan (e.g. {@code trekking}).
     * NULL for IMPORTED tracks and legacy PLANNED tracks saved before migration 027.
     * Used by the planner UI so re-loading a plan recomputes with the same profile
     * rather than silently falling back to the default.
     */
    @Column(name = "planner_profile", length = 64)
    private String plannerProfile;

    /**
     * Versioned planner-specific payload for PLANNED tracks. Stores the saved
     * route result (currently legs + aggregate stats) in one extensible JSON
     * document so future planner metadata can be added without more narrow
     * columns.
     */
    @Column(name = "planner_route_json", columnDefinition = "text")
    private String plannerRouteJson;

    private Date createDate = new Date();

    private Date updateDate = new Date();

    /**
     * Entity revision managed exclusively by a DB trigger (trg_gps_track_version).
     * Hibernate reads the value after INSERT/UPDATE but never writes it.
     * 0 on INSERT, incremented on every UPDATE — covers Hibernate, raw SQL, scripts.
     */
    @Column(insertable = false, updatable = false, columnDefinition = "bigint not null default 0")
    @org.hibernate.annotations.Generated
    private Long version;

    /**
     * Safely appends a message with a newline to loadMessages, respecting the column limit.
     *
     * @param message the message to append
     */
    public void addLoadMessage(String message) {
        if (message == null || message.isEmpty()) {
            return;
        }
        if (this.loadMessages == null) {
            this.loadMessages = "";
        }
        StringBuilder builder = new StringBuilder(this.loadMessages);
        if (!builder.isEmpty()) {
            builder.append("\n");
        }
        builder.append("- ").append(message);

        // Ensure we don't exceed the 8000 char DB limit
        int maxLength = 7900;
        if (builder.length() > maxLength) {
            String truncationSuffix = "... [truncated]";
            builder.setLength(maxLength - truncationSuffix.length());
            builder.append(truncationSuffix);
        }
        this.loadMessages = builder.toString();
    }

    @PrePersist
    protected void onCreate() {
        if (this.createDate == null) {
            this.createDate = new Date();
        }
        this.updateDate = new Date();
    }

}
